Csv related stuff (Work in progress)
yakworks/gorm-tools pull request #416
Opened 2021-12-06 16:42 UTC by snimavat

2021-12-07 00:40 UTC, jdabal commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVMapReader.groovy
> +
use PathKeyMap

2021-12-08 13:40 UTC, snimavat commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVMapReader.groovy
> +
CsvPathMapkey reader is used now

2021-12-08 17:35 UTC, basejump commented on gorm-tools/src/test/groovy/gorm/tools/databinding/EntityMapBinderUnitSpec.groovy
> +    void "test bind using PathKeyMap"() {
break into its own test

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/test/groovy/gorm/tools/csv/CSVReaderUtilsTest.groovy
> +class CSVReaderUtilsTest extends GroovyTestCase{
remove this

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/test/groovy/gorm/tools/csv/CSVMapReaderTest.groovy
> +class CSVMapReaderTest extends GroovyTestCase {
remove?

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/test/groovy/gorm/tools/csv/CSVMapReaderBatchTest.groovy
> +class CSVMapReaderBatchTest extends GroovyTestCase {
remove

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVReaderUtils.groovy
> +class CSVReaderUtils {
remove, is this helpful?

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVPathKeyMapReader.groovy
> +@Builder(builderStrategy = SimpleStrategy, prefix = "")
lets add simple javadoc, bread crumb on what this is for

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVPathKeyMapReader.groovy
> +    List<Map<String, String>> readAllRows() {
is this override? is there a super method that does this?

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVMapReader.groovy
> +class CSVMapReader implements Closeable, Iterable {
dod we need this? remove

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/grails-app/conf/application.yml
> +---
skinny down to just what we need, see gorm-tools-security for example

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/grails-app/conf/application.groovy
> +grails {
this needed?

2021-12-08 17:35 UTC, basejump commented on gorm-test-domain/src/main/groovy/yakworks/gorm/testing/model/KitchenSinkRepo.groovy
> +    void doAssociations(KitchenSink kitchenSink, Map data) {
this is not called, do we not need it?

2021-12-08 17:35 UTC, basejump commented on gorm-tools-csv/src/test/groovy/gorm/tools/csv/CSVPathKeyMapReaderSpec.groovy
> +            Map row = sinkItemReader.readMap() { PathKeyMap m ->
are we not going to use closure? add comments/bread crumbs on whats going on here

2021-12-08 17:35 UTC, basejump commented on examples/benchmarks/src/main/groovy/gpbench/helpers/csv/CSVMapReader.groovy
> +class CSVMapReader implements Closeable, Iterable {
remove if we dont need it, which I dont see why we do.

2021-12-08 17:35 UTC, basejump requested changes
see review

2021-12-09 19:37 UTC, jdabal commented on gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVPathKeyMapReader.groovy
> +    List<Map<String, String>> readAllRows() {
rename readAllRows to readAllLines

2021-12-09 19:46 UTC, merged