Delete location before contact delete 9ci/domain9#477
yakworks/gorm-tools pull request #565
Opened 2022-09-14 14:04 UTC by snimavat

connect 9ci/domain9#477

2022-09-14 14:06 UTC, snimavat commented
@basejump ContactSource gets deleted as cascade delete as per mapping - test verifies it.
I have updated to remove contact location.

We have this `Contact.groovy`
```
        flex cascade: "all"
        emails cascade: "all-delete-orphan"
        phones cascade: "all-delete-orphan"
        sources cascade: "all-delete-orphan"
```

2022-09-15 08:55 UTC, basejump requested changes

2022-09-15 08:55 UTC, basejump commented on rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy
> -        // ContactSource.query(contact: contact).deleteAll()
what happened to ContactSource?

2022-09-15 08:55 UTC, basejump commented on rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy
> -        Location.executeUpdate("update Location set contact = null where contact = :contact", [contact: contact]) //set contact to null
@jdabal this was done like this another CED hack. can you check into it. was some kind of special contact for bill to or something that had the location assigned. I looked into some months back

2022-12-06 04:27 UTC, snimavat commented
New PR here - https://github.com/yakworks/gorm-tools/pull/599

2022-12-06 07:22 UTC, snimavat commented
Done here - https://github.com/yakworks/gorm-tools/pull/599

2022-12-06 07:22 UTC, closed without merging