reproduce isDirty error
yakworks/gorm-tools pull request #696
Opened 2023-06-26 16:38 UTC by snimavat

2023-06-27 00:37 UTC, basejump requested changes

2023-06-27 00:37 UTC, basejump commented on examples/testify/src/integration-test/groovy/gorm/tools/SanityCheckSpec.groovy
> +    void "check isDirty throws error"() {
can we get a series in IsDirtySpec in gorm-tools? does it need to be integrationTest? what works and what does not? can we fix it? what do we do and what do we use? this isn't telling us to much.

2023-07-11 21:36 UTC, basejump requested changes

2023-07-11 21:36 UTC, basejump commented on examples/testify/src/integration-test/groovy/gorm/tools/repository/HasChangedIntegrationSpec.groovy
> +    void "PROBLEM - remains dirty untill flush"() {
@snimavat this is the one we need to sort out. why does it show hasChanged until its flushed but that does not seem to be required on the first persist?

2023-07-13 11:45 UTC, snimavat commented
@basejump Here's what is happening 

1. Dirty status is stored in `$changedProperties` which is null initially 
2. `instance.hasChanged()` returns true if `$changedProperties` is null (thts strange)
3. **New instance is always dirty untill saved** : That is because it has `$changedProperties` = null
4. **New instance is not dirty after save, even without flush** : 
     - That is because `ClosureEventTriggeringInterceptor.activateDirtyChecking` sets  `$changedProperties` to empty list if its null. 
     - `ClosureEventTriggeringInterceptor gets called during hibernate's `saveOrUpdate event` that even fires even without flush
5. **Existing instance is dirty untill saved with flush**
    - In this case dirty status is reset by `GrailsEntityDirtinessStrategy.resetDirty` which implements a `CustomEntityDirtinessStrategy`
    - Dirty status does not get reset during  `saveOrUpdate event`  like in the case of new, because,  `ClosureEventTriggeringInterceptor` does that only if `changedProperties` is null. but it is not null in this case, which is unlike the case for new instance.

2023-08-09 22:03 UTC, merged