Querytimeout refactor - remove listeners
yakworks/gorm-tools pull request #800
Opened 2024-05-31 14:50 UTC by snimavat

2024-06-05 15:33 UTC, basejump commented
@snimavat this is a good idea. How do we set it for the users in controller?

2024-06-12 15:01 UTC, snimavat commented
> @snimavat this is a good idea. How do we set it for the users in controller?

Made changes to EntityResponder

2024-07-30 16:50 UTC, basejump requested changes
see https://github.com/yakworks/gorm-tools/pull/812 for start of refactor

2024-07-30 16:50 UTC, basejump commented on gorm-tools/src/main/groovy/gorm/tools/hibernate/GormToolsTrxManagerBeanPostProcessor.groovy
> - * NOTE: THIS IS NOT USED BUT WE MIGHT COME BACK TO IT. KEPT FOR LATER USE
keep this for reference

2024-08-05 15:38 UTC, merged