Support lookup for cross ref insert/update
yakworks/gorm-tools pull request #819
Opened 2024-09-17 13:37 UTC by snimavat

9ci/cust-rndc-ext#584

2024-09-17 18:58 UTC, basejump requested changes

2024-09-18 12:39 UTC, snimavat commented on rally-domain/src/integration-test/groovy/yakworks/rally/activity/ActivityContactOpTests.groovy
> +            contacts: JsonEngine.toJson([[id: contacts[3].id], [id: contacts[4].id]])
Done

2024-09-20 16:52 UTC, basejump requested changes

2024-09-20 16:52 UTC, basejump commented on rally-domain/src/integration-test/groovy/yakworks/rally/activity/ActivityContactOpTests.groovy
> +            contacts: "[{\"id\": \"${contacts[3].id}\"}, {\"id\": \"${contacts[4].id}\"}]".toString()
whats wrong with `'[{"id": "${contacts[3].id}"}....'` , why are you escaping quotes and making it so hard to read?

2024-09-20 18:45 UTC, basejump requested changes

2024-09-21 00:32 UTC, merged