Syncjog GET : Add dates
yakworks/gorm-tools pull request #855
Opened 2024-12-06 14:53 UTC by snimavat

2024-12-09 14:03 UTC, snimavat commented
@basejump

SyncJobCrudApi overrides `entityToMap` and calls `JobUtils.convertToMap(job)`
so default implementation which creates meta map from includes doesnt work

2024-12-11 09:36 UTC, snimavat commented
Done

2024-12-13 17:25 UTC, basejump requested changes

2024-12-13 17:25 UTC, basejump commented on gorm-rest/src/main/groovy/yakworks/rest/gorm/render/SyncJobRenderer.groovy
> +//XXX is this used now, since we have SyncjobCrudApi
👀

2024-12-13 17:25 UTC, basejump commented on gorm-tools/src/main/groovy/gorm/tools/job/JobUtils.groovy
>              id: job['id'],
👀 look at original code, do we have every field? I think we are missing tests for "problem"

2024-12-16 16:44 UTC, jdabal approved these changes

2024-12-16 19:51 UTC, merged